### ISSUE TITLE
Plans to maintain this?

### ISSUE THREAD

**Issue by shellster** [darinkes/SshNet.Agent#1]
Sorry to open this as an issue, but I don't know how else to get in contact with you. 

With regard to this thread: https://github.com/sshnet/SSH.NET/issues/31#issuecomment-803246831

It appears that the SshNet team has no desire to make the modifications necessary for this repo to function without manually patching and building their library.  I would like to implement this in this project https://github.com/shellster/keepass-sftp-sync pursuant to our conversation in the above mentioned thread.  What is your current plan with this library?  Do you plan to maintain it or a fork of SshNet?

**Comment by darinkes** [comment]
Hm, I'm optimistic regarding the needed changes. Just takes some time and discussion.

Pretty sure we can work something out to make my extensions work with upstream SSH.NET.
To fork and maintain something else is not an option.

**Comment by darinkes** [comment]
Updated this Project to use the current SSH.NET Release 2023.
Beta-Packages are available via Nuget.org.
