### ISSUE TITLE
NuGet unable to resolve dependencies

### ISSUE THREAD

**Issue by LordZZT** [darinkes/SshNet.Agent#2]
Howdy, I'm having a dumb issue.

I'm attempting to install form NuGet targeting '.NETFramework,Version=v4.6.1'

`Attempting to resolve dependencies for package 'SshNet.Agent.0.1.0-beta' with DependencyBehavior 'Lowest'
Unable to find a version of 'SshNet.Security.Cryptography' that is compatible with 'Renci.SshNet 1.0.0 constraint: SshNet.Security.Cryptography (= 1.2.0)'.`

**Comment by darinkes** [comment]
Hi, not a dumb issue :)

See the note in the Readme: https://github.com/darinkes/SshNet.Agent#status

This Extension is still WIP and needs changes in SSH.NET which are not merged yet.
So the Nuget doesn't work right now without building it yourself.

**Comment by LordZZT** [comment]
Perfect, thanks for the follow up
